version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auction-app-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb+srv://auctionuser:J6jDFroWlbwCIBMh@auction-app.awyii8w.mongodb.net/?retryWrites=true&w=majority&appName=auction-app
      - JWT_SECRET=mysecretkey123
      - EMAIL_USER=kartavyachauhan2005@gmail.com
      - EMAIL_PASS=3Uh><9kT
      - CORS_ORIGIN=http://localhost:8080
    ports:
      - "3000:5000"
    volumes:
      - ./backend/logs:/app/logs
      - ./uploads:/uploads
    networks:
      - auction-network

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: auction-app-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - auction-network
  
  # Redis service
  redis:
    image: redis:alpine
    container_name: auction-app-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - auction-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auction-app-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
